
package br.com.administrador.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IntegrationUserComponentImplService", targetNamespace = "http://soap.administrador.com.br/", wsdlLocation = "http://localhost:8080/administrator-component/IntegrationUserComponent?wsdl")
public class IntegrationUserComponentImplService
    extends Service
{

    private final static URL INTEGRATIONUSERCOMPONENTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException INTEGRATIONUSERCOMPONENTIMPLSERVICE_EXCEPTION;
    private final static QName INTEGRATIONUSERCOMPONENTIMPLSERVICE_QNAME = new QName("http://soap.administrador.com.br/", "IntegrationUserComponentImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/administrator-component/IntegrationUserComponent?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTEGRATIONUSERCOMPONENTIMPLSERVICE_WSDL_LOCATION = url;
        INTEGRATIONUSERCOMPONENTIMPLSERVICE_EXCEPTION = e;
    }

    public IntegrationUserComponentImplService() {
        super(__getWsdlLocation(), INTEGRATIONUSERCOMPONENTIMPLSERVICE_QNAME);
    }

    public IntegrationUserComponentImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTEGRATIONUSERCOMPONENTIMPLSERVICE_QNAME, features);
    }

    public IntegrationUserComponentImplService(URL wsdlLocation) {
        super(wsdlLocation, INTEGRATIONUSERCOMPONENTIMPLSERVICE_QNAME);
    }

    public IntegrationUserComponentImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTEGRATIONUSERCOMPONENTIMPLSERVICE_QNAME, features);
    }

    public IntegrationUserComponentImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegrationUserComponentImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IntegrationUserComponent
     */
    @WebEndpoint(name = "IntegrationUserServicePort")
    public IntegrationUserComponent getIntegrationUserServicePort() {
        return super.getPort(new QName("http://soap.administrador.com.br/", "IntegrationUserServicePort"), IntegrationUserComponent.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegrationUserComponent
     */
    @WebEndpoint(name = "IntegrationUserServicePort")
    public IntegrationUserComponent getIntegrationUserServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.administrador.com.br/", "IntegrationUserServicePort"), IntegrationUserComponent.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTEGRATIONUSERCOMPONENTIMPLSERVICE_EXCEPTION!= null) {
            throw INTEGRATIONUSERCOMPONENTIMPLSERVICE_EXCEPTION;
        }
        return INTEGRATIONUSERCOMPONENTIMPLSERVICE_WSDL_LOCATION;
    }

}
