
package br;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TokenValidateService", targetNamespace = "http://service.soap.pos3.ifpb.edu.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface TokenValidateService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.soap.pos3.ifpb.edu.br/TokenValidateService/tokenValidateServiceRequest", output = "http://service.soap.pos3.ifpb.edu.br/TokenValidateService/tokenValidateServiceResponse")
    public boolean tokenValidateService(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
