
package br;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TokenValidateServiceImplService", targetNamespace = "http://service.soap.pos3.ifpb.edu.br/", wsdlLocation = "http://localhost:8080/ifpb-pos3-autenticator-component-web/token-validate?wsdl")
public class TokenValidateServiceImplService
    extends Service
{

    private final static URL TOKENVALIDATESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TOKENVALIDATESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TOKENVALIDATESERVICEIMPLSERVICE_QNAME = new QName("http://service.soap.pos3.ifpb.edu.br/", "TokenValidateServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.1.103:8080/ifpb-pos3-autenticator-component-web/token-validate?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOKENVALIDATESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TOKENVALIDATESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TokenValidateServiceImplService() {
        super(__getWsdlLocation(), TOKENVALIDATESERVICEIMPLSERVICE_QNAME);
    }

    public TokenValidateServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOKENVALIDATESERVICEIMPLSERVICE_QNAME, features);
    }

    public TokenValidateServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TOKENVALIDATESERVICEIMPLSERVICE_QNAME);
    }

    public TokenValidateServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOKENVALIDATESERVICEIMPLSERVICE_QNAME, features);
    }

    public TokenValidateServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TokenValidateServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TokenValidateService
     */
    @WebEndpoint(name = "TokenValidateServiceImplPort")
    public TokenValidateService getTokenValidateServiceImplPort() {
        return super.getPort(new QName("http://service.soap.pos3.ifpb.edu.br/", "TokenValidateServiceImplPort"), TokenValidateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TokenValidateService
     */
    @WebEndpoint(name = "TokenValidateServiceImplPort")
    public TokenValidateService getTokenValidateServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap.pos3.ifpb.edu.br/", "TokenValidateServiceImplPort"), TokenValidateService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOKENVALIDATESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TOKENVALIDATESERVICEIMPLSERVICE_EXCEPTION;
        }
        return TOKENVALIDATESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
